#!/usr/bin/env python3

from os import environ
from time import sleep

import paho.mqtt.publish
import requests
from milc import cli

cli.milc_options(name='openweathermaps2mqtt', author='zwhite')


TEMPERATURE_KEYS = ('temp', 'feels_like', 'dew_point')


def get_weather(url):
    """Fetch weather data from openweathermaps.
    """
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return r.json()


def make_msg(topic, payload, qos):
    cli.log.debug('Queuing for MQTT: %s: %s', topic, payload)
    return {'topic': topic, 'payload': payload, 'qos': qos, 'retain': True}


def flatten_json(json_obj, sep='/'):
    """Recursively parse a JSON object to produce a flattened namespace.

    Arguments:

        json_obj
            The JSON object to flatten.

        sep
            The character to indicate nesting levels with. Default: /
    """
    out = {}

    def flatten(local_obj, name=''):
        if isinstance(local_obj, dict):
            for key in local_obj:
                new_name = (name + sep + key) if name else key
                flatten(local_obj[key], new_name)

        elif isinstance(local_obj, list):
            for i, key in enumerate(local_obj):
                new_name = (name + sep + str(i)) if name else str(i)
                flatten(key, new_name)

        else:
            out[name] = local_obj

    flatten(json_obj)

    return out


def in_skiplist(key, skip_list):
    """Returns True if key starts with one of the words in skip_list.
    """
    for skip_key in skip_list:
        if key.startswith(skip_key):
            return True

    return False


def is_temperature(key):
    """Returns True if key is a temperature.
    """
    topic_parts = key.split('/')

    return topic_parts[-1] in TEMPERATURE_KEYS or topic_parts[-2] in TEMPERATURE_KEYS


def C_to_F(temperature_C):
    """Converts temperature_C to temperature_F.
    """
    if temperature_C is None:
        return None
    return (float(temperature_C) * 9/5) + 32


@cli.argument('--weather-url', default=environ.get('WEATHER_URL'), required=not environ.get('WEATHER_URL'), help='OpenWeatherMap One Call API URL')
@cli.argument('--mqtt-host', default=environ.get('MQTT_HOST', 'localhost'), help='MQTT broker hostname')
@cli.argument('--mqtt-port', default=int(environ.get('MQTT_PORT', '1883')), type=int, help='MQTT broker port')
@cli.argument('--mqtt-qos', default=int(environ.get('MQTT_QOS', '1')), type=int, help='MQTT QoS level')
@cli.argument('--mqtt-topic', default=environ.get('MQTT_TOPIC', 'weather'), help='MQTT topic prefix')
@cli.argument('--mqtt-client-id', default=environ.get('MQTT_CLIENT_ID', 'openweathermaps2mqtt'), help='MQTT client ID')
@cli.argument('--skip-list', default=environ.get('SKIP_LIST', 'lat,lon,timezone,timezone_offset'), help='Comma-separated keys to skip')
@cli.argument('--wait-time', default=int(environ.get('WAIT_TIME', '3600')), type=int, help='Seconds between fetches')
@cli.argument('--dry-run', action='store_true', default=False, help='Print messages without publishing to MQTT')
@cli.entrypoint('Fetch weather data from OpenWeatherMap and publish to MQTT')
def main(cli):
    skip_list = cli.args.skip_list.replace(' ', '').split(',')

    while True:
        try:
            weather_data = get_weather(cli.args.weather_url)
            msgs = []
            for key, value in flatten_json(weather_data).items():
                if in_skiplist(key, skip_list):
                    pass
                elif is_temperature(key):
                    msgs.append(make_msg(f'{cli.args.mqtt_topic}/{key}_C', value, cli.args.mqtt_qos))
                    msgs.append(make_msg(f'{cli.args.mqtt_topic}/{key}_F', C_to_F(value), cli.args.mqtt_qos))
                else:
                    msgs.append(make_msg(f'{cli.args.mqtt_topic}/{key}', value, cli.args.mqtt_qos))
            if not cli.args.dry_run:
                paho.mqtt.publish.multiple(msgs, hostname=cli.args.mqtt_host, port=cli.args.mqtt_port, client_id=cli.args.mqtt_client_id)
            else:
                cli.log.info('Dry run: %d messages not published', len(msgs))

        except requests.exceptions.RequestException as e:
            cli.log.error('Could not fetch weather: %s: %s', e.__class__.__name__, e)
        except Exception as e:
            cli.log.error('%s: %s', e.__class__.__name__, e)
            cli.log.exception('MQTT publish failed')
            raise

        cli.log.debug('Sleeping %d seconds...', cli.args.wait_time)
        sleep(cli.args.wait_time)


if __name__ == '__main__':
    cli()
